---
swagger: "2.0"
info:
  description: "This is the documentation for this project"
  version: "0.0.1"
  title: "Swagger Genrated Files Example"
paths:
  /crud/Clients:
    get:
      operationId: "getClients"
      parameters: []
      responses:
        200:
          description: ""
    post:
      operationId: "createClient"
      parameters:
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Client"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
  /crud/Clients/{id}:
    get:
      operationId: "getById"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: ""
    put:
      operationId: "updateClient"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Client"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
    delete:
      operationId: "deleteClient"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "string"
definitions:
  Client:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      lastName:
        type: "string"
      age:
        type: "string"
      gender:
        type: "string"
